### ISSUE TITLE
Patch sync doesn't work

### ISSUE THREAD

**Issue by ndmitchell** [mislav/issuesync#3]
When I run on a repo with patches, e.g. http://github.com/ndmitchell/shake, I get:

```
Aborted: GitHub API returned 302 "Found"
<html><body>You are being <a href="https://patch-diff.githubusercontent.com/raw/ndmitchell/shake/pull/416.patch">redirected</a>.</body></html>
```

I think following redirects, as described (here)[http://stackoverflow.com/a/6934503/160673], would probably solve the issue.

**Comment by mislav** [comment]
Thanks for reporting! I haven't used this in a while 😅

**Comment by ndmitchell** [comment]
Thanks - I work on my issues on the train every morning, without internet, so it is very useful to me.
