### ISSUE TITLE
Doesn't work with a proxy server

### ISSUE THREAD

**Issue by ndmitchell** [mislav/issuesync#5]
I connect to the internet via a proxy server, and following standard conventions, I set my `$http_proxy` and `$https_proxy` variables. By default, the library you are using doesn't use them, but by adding:

        conn.proxy = :ENV

In `ApiClient.http` I can get it working. I don't know if adding such an incantation breaks users who don't go through a proxy, or if there is a better approach.

**Comment by mislav** [comment]
Good thought thanks!

**Comment by ndmitchell** [comment]
Thanks - I confirm this approach works for me.
