### ISSUE TITLE
Ignore submodules

### ISSUE THREAD

**Issue by dcecile** [mislav/issuesync#6]
My local Git repository has a submodule definition for a module hosted on GitHub, and that's the repository that got picked for syncing issues.

As a local hack, I changed [the code](https://github.com/mislav/issuesync/blob/9a6cf764cedb7ac8f59c00da42ecfa47a32ff6fc/issuesync.rb#L269) to reverse the lines in the config file before looking for GitHub URLs, and this lets me continue using the tool.

Here's what my `.git/config` file looks like:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[submodule "lib/serpent"]
	url = https://github.com/pkulchenko/serpent.git
[remote "origin"]
	url = git@github.com:dcecile/ultra-rainbow-bake-sale.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

**Comment by mislav** [comment]
That's a good catch! Would you send a pull request that changes `File.readlines('.git/config')` to `` `git remote -v`.lines``? Reading only URLs from remotes would avoid even reading any submodule URLs.

**Comment by dcecile** [comment]
:bulb: Oh, that's good idea. I was thinking the solution would involve (A) more complicated config file parsing, or (B) integrating a git Ruby library.
